name: NotificationTest
options:
  bundleIdPrefix: com.tonygo.notif
  deploymentTarget:
    iOS: "17.2"
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone
    SUPPORTS_MACCATALYST: NO
targets:
  NotificationTest:
    type: application
    platform: iOS
    sources:
      - path: NotificationTest.swift
    infoPlist: Info.plist
    framework: 
      - UIKit.framework
      - UserNotifications.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.tonygo.notif"
        INFOPLIST_FILE: Info.plist
